name: k_chart
description: A Flutter K Chart.
version: 0.6.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: ^0.18.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
